### ISSUE TITLE
Data split names

### ISSUE THREAD

**Issue by dfulu** [alan-turing-institute/cloudcasting#27]
In the download make sure that the different data splits are saved with the agreed names

- 2 weekly 2022 - "test_2022"
- 2023 - "verify_2023"
- up to end 2021 and alternate fortnights in 2022 - "train(ing)"

Also

Produce error for 2023, unless specify verify
Make sure dataset is not empty

**Comment by IFenton** [comment]
Addressing this in [IFenton-27-data-download](https://github.com/alan-turing-institute/cloudcasting/tree/IFenton-27-data-download)
