### ISSUE TITLE
pre-commit issue with types-pkg-resources

### ISSUE THREAD

**Issue by IFenton** [alan-turing-institute/cloudcasting#34]
I can't get pre-commit working on my computer. This seems to be because the dependency `types-all` requires `types-pkg-resources` which has been yanked from PyPI - https://pypi.org/project/types-pkg-resources/#history. So `types-all` fails to install

**Comment by phinate** [comment]
Yes, I hit this a week or two ago. Thanks for reporting! I added `types-all` as a stop-gap to be lazy and not track down individual typing packages, but we can definitely just do that.
