### ISSUE TITLE
Baskerville / wandb integration

### ISSUE THREAD

**Issue by IFenton** [alan-turing-institute/cloudcasting#51]
It occurs to me that there might be issues with logging in to wandb from Baskerville, so if people are using Baskerville for the model validation we might need to create a two step process - run the validation on Baskerville and return then output. Then run the wandb step on that returned output on a personal computer. (It might work fine however)

**Comment by evangeline-corcoran** [comment]
I tested using the model validation process from Baskerville last week for some optical flow models, and there was no issue running it wandb step
