### ISSUE TITLE
Provide a mask relative to the original image that closely hugs the UK

### ISSUE THREAD

**Issue by phinate** [alan-turing-institute/cloudcasting#79]
We discussed that for validation, we should crop our original canvas size of [372, 614] to an area over the UK that more closely resembles the area that's actually used for solar PV forecasts. This will make our validation procedure more representative of how models are used downstream.

Storing this mask in `cloudcasting.constants` would be ideal, such that `image[MASK]` gives us the right image.

Links to #77, PR in #78.

**Comment by IFenton** [comment]
Closed with #78
